/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#4059aa",
        "on-primary-fixed": "#002201",
        "on-secondary": "#ffffff",
        "primary-fixed": "#bcf0ae",
        "primary-container": "#2d5a27",
        "outline": "#72796e",
        "on-background": "#1a1c1c",
        "surface-tint": "#3b6934",
        "on-tertiary-fixed-variant": "#71314c",
        "on-surface-variant": "#42493e",
        "surface-container": "#eeeeed",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#1d3989",
        "tertiary": "#60233e",
        "surface-variant": "#e3e2e1",
        "on-tertiary-container": "#ffaac8",
        "on-primary-container": "#9dd090",
        "secondary-container": "#8fa7fe",
        "primary": "#154212",
        "surface-dim": "#dadad9",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b6c4ff",
        "primary-fixed-dim": "#a1d494",
        "inverse-surface": "#2f3130",
        "on-surface": "#1a1c1c",
        "tertiary-fixed-dim": "#ffb0cc",
        "surface-container-low": "#f4f3f2",
        "tertiary-fixed": "#ffd9e4",
        "on-primary": "#ffffff",
        "surface": "#faf9f8",
        "surface-container-highest": "#e3e2e1",
        "background": "#faf9f8",
        "surface-container-high": "#e9e8e7",
        "on-secondary-fixed-variant": "#264191",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#23501e",
        "inverse-on-surface": "#f1f0f0",
        "inverse-primary": "#a1d494",
        "outline-variant": "#c2c9bb",
        "on-tertiary-fixed": "#3b0520",
        "secondary-fixed": "#dce1ff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#00164e",
        "tertiary-container": "#7c3a55",
        "surface-bright": "#faf9f8",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Newsreader", "Manrope", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
